all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file:
      "{{ lookup('env','HOME') }}/.ssh/two-tauers-ansible"
    master_ip: "{{ groups['master'][0] }}"
    k3s_version: v1.19.15+k3s2
    systemd_dir: /etc/systemd/system

    # ansible_user: ansible
    # extra_agent_args: '
    # extra_server_args: '
    # k3s_version: v1.19.15+k3s2
    # ssh_key: '{{ lookup('env','HOME') }}/.ssh/2tauers_ansible'
    # systemd_dir: /etc/systemd/system

  children:
    k3s_cluster:
      children:
        master:
          hosts:
            192.168.0.100
        node:
          hosts:
            192.168.0.101
            # 192.168.0.102
            # 192.168.0.103
