---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file:
      "{{ lookup('env','HOME') }}/.ssh/two-tauers-ansible"
    master_ip: "{{ groups['master'] | map('extract', hostvars, ['ansible_host']) | first }}"
    k3s_version: v1.23.1+k3s2
    systemd_dir: /etc/systemd/system

  children:
    k3s_cluster:
      children:
        master:
          hosts:
            sauron:
              ansible_host: 192.168.0.100
        node:
          hosts:
            orker1:
              ansible_host: 192.168.0.101
            orker2:
              ansible_host: 192.168.0.102
            orker3:
              ansible_host: 192.168.0.103
